apiVersion: apps/v1
kind: Deployment
metadata:
  name: rkassel-playground
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playground # Tag to link with the service
  template:
    metadata:
      labels:
        app: playground
    spec:
      containers:
      - name: container-www
        image: rkassel/playground:v1
        ports:
        - containerPort: 8888